import type { Question } from './engine';

// The live assessment is intentionally separate from the legacy question bank.
// Only these focused questions affect the free Snapshot and paid Reset.
export const ASSESSMENT_QUESTIONS: Question[] = [
  {
    id: 'name',
    type: 'text',
    chapter: 'Let’s begin gently',
    title: 'First — what should we call you?',
    subtitle: 'Your result will use your first name so it is easier to read and save privately.',
    placeholder: 'Your first name…',
    motivation: 'Begin the assessment →',
  },
  {
    id: 'age_range',
    type: 'qcm',
    chapter: 'A little context',
    title: 'Which age range are you in?',
    subtitle: 'This gives context to the relationship timeline you describe; it does not determine your pattern.',
    options: [
      { label: '18 – 24', scores: {} },
      { label: '25 – 34', scores: {} },
      { label: '35 – 44', scores: {} },
      { label: '45+', scores: {} },
    ],
    motivation: 'Continue →',
  },
  {
    id: 'single_duration',
    type: 'qcm',
    chapter: 'Chapter I — Where you are now',
    title: 'How long have you been single?',
    subtitle: 'Choose the answer that best matches your current situation.',
    options: [
      { label: 'Less than a year', sub: 'A recent transition', scores: { anxious: 1 } },
      { label: '1 – 3 years', sub: 'A meaningful stretch of time', scores: { fearful: 1 } },
      { label: '3 – 5 years', sub: 'Long enough to notice recurring choices', scores: { avoidant: 1 } },
      { label: 'More than 5 years', sub: 'A longer period of being on your own', scores: { avoidant: 1, fearful: 1 } },
      { label: 'I’ve never had a serious relationship', sub: 'There may still be useful patterns in attraction and avoidance', scores: { fearful: 1, anxious: 1 } },
    ],
    motivation: 'Continue honestly →',
  },
  {
    id: 'home_climate',
    type: 'qcm',
    chapter: 'Chapter II — Early relationship experiences',
    title: 'Growing up, your home generally felt…',
    subtitle: 'This is context for reflection, not a diagnosis or a claim about one cause.',
    options: [
      { label: 'Safe and warm', sub: 'Care felt steady and predictable', scores: { secure: 2 } },
      { label: 'Loving, but unpredictable', sub: 'The emotional atmosphere changed often', scores: { anxious: 2 } },
      { label: 'Emotionally distant', sub: 'Practical needs may have been easier to discuss than feelings', scores: { avoidant: 2 } },
      { label: 'Tense — I walked on eggshells', sub: 'You often monitored the mood around you', scores: { fearful: 2 } },
    ],
    motivation: 'Continue →',
  },
  {
    id: 'father_figure',
    type: 'qcm',
    chapter: 'Chapter II — Early relationship experiences',
    title: 'Your father or father figure was generally…',
    subtitle: 'This answer may add context, but it does not by itself explain your adult relationships.',
    options: [
      { label: 'Present and affectionate', sub: 'Emotional connection felt available', scores: { secure: 2 } },
      { label: 'Present, but emotionally unavailable', sub: 'Physically present, emotionally difficult to reach', scores: { anxious: 2 } },
      { label: 'Mostly absent', sub: 'Physically or emotionally not consistently available', scores: { anxious: 1, fearful: 1 } },
      { label: 'Inconsistent', sub: 'Warm at times and distant at others', scores: { anxious: 1, fearful: 1 } },
      { label: 'Strict or hard to please', sub: 'Approval often felt connected to performance', scores: { anxious: 2, avoidant: 1 } },
    ],
    motivation: 'Continue →',
  },
  {
    id: 'child_comfort',
    type: 'qcm',
    chapter: 'Chapter II — Early relationship experiences',
    title: 'As a child, when you were hurting and needed comfort…',
    subtitle: 'Choose the response that happened most often, even if your experience was mixed.',
    options: [
      { label: 'I received it', sub: 'Someone was usually emotionally available', scores: { secure: 2 } },
      { label: 'I learned not to ask', sub: 'Handling it alone felt easier or safer', scores: { avoidant: 2 } },
      { label: 'I comforted others instead', sub: 'You often became the responsible one', scores: { anxious: 1, avoidant: 1 } },
      { label: 'It depended on their mood', sub: 'Support did not always feel predictable', scores: { anxious: 2 } },
    ],
    motivation: 'Continue →',
  },
  {
    id: 'breakup_pattern',
    type: 'qcm',
    chapter: 'Chapter III — Previous relationships',
    title: 'Your past relationships most often ended because…',
    subtitle: 'Select the closest pattern, not a perfect description of every relationship.',
    options: [
      { label: 'I pulled away first', sub: 'Distance felt safer than greater vulnerability', scores: { avoidant: 2 } },
      { label: 'They left me', sub: 'The ending was usually initiated by the other person', scores: { anxious: 2 } },
      { label: 'A slow, silent fade', sub: 'Contact and effort gradually disappeared', scores: { avoidant: 1, fearful: 1 } },
      { label: 'Explosive endings', sub: 'Conflict or intensity escalated before the ending', scores: { fearful: 2 } },
    ],
    motivation: 'Continue →',
  },
  {
    id: 'exes_pattern',
    type: 'qcm',
    chapter: 'Chapter III — Previous relationships',
    title: 'Looking across previous partners, what do you notice most?',
    subtitle: 'Focus on observable behavior rather than labels or imagined potential.',
    options: [
      { label: 'They were emotionally unavailable', sub: 'Closeness or clarity remained limited', scores: { anxious: 2 } },
      { label: 'I chose potential over reality', sub: 'What the relationship could become carried a lot of weight', scores: { anxious: 1, fearful: 1 } },
      { label: 'Intense at first, then cold', sub: 'Early attention did not become steady connection', scores: { fearful: 2 } },
      { label: 'I lost myself in them', sub: 'My needs, routines, or priorities became less visible', scores: { anxious: 2 } },
      { label: 'Honestly — no clear pattern', sub: 'The remaining questions may still reveal useful responses', scores: { avoidant: 1 } },
    ],
    motivation: 'Continue →',
  },
  {
    id: 'he_pulls_away',
    type: 'qcm',
    chapter: 'Chapter IV — How you respond now',
    title: 'When someone you like pulls away, you usually…',
    subtitle: 'Choose your first impulse, even when you do not always act on it.',
    options: [
      { label: 'Move closer, text more', sub: 'I try to restore connection quickly', scores: { anxious: 2 } },
      { label: 'Match his distance', sub: 'I protect myself by becoming equally distant', scores: { avoidant: 2 } },
      { label: 'Overthink every word I said', sub: 'I review the interaction for what went wrong', scores: { anxious: 1, fearful: 1 } },
      { label: 'Calmly ask what’s going on', sub: 'I prefer one direct question over guessing', scores: { secure: 2 } },
    ],
    motivation: 'Continue →',
  },
  {
    id: 'conflict_style',
    type: 'qcm',
    chapter: 'Chapter IV — How you respond now',
    title: 'During conflict with a partner, you tend to…',
    subtitle: 'Select the response that appears when the disagreement matters emotionally.',
    options: [
      { label: 'Explode, then regret it', sub: 'The feeling becomes intense before I can organize it', scores: { fearful: 2 } },
      { label: 'Shut down completely', sub: 'I become quiet or unavailable', scores: { avoidant: 2 } },
      { label: 'Over-apologize to end it fast', sub: 'Relief can become more urgent than expressing my view', scores: { anxious: 2 } },
      { label: 'Talk it through calmly', sub: 'I can stay engaged while discussing the problem', scores: { secure: 2 } },
    ],
    motivation: 'Continue →',
  },
  {
    id: 'falling_style',
    type: 'qcm',
    chapter: 'Chapter IV — How you respond now',
    title: 'You usually develop strong feelings…',
    subtitle: 'Think about pace and availability, not whether the feelings were right or wrong.',
    options: [
      { label: 'Fast and hard', sub: 'Emotional investment grows within weeks', scores: { anxious: 2 } },
      { label: 'Slowly, behind high walls', sub: 'Trust requires substantial proof before I open up', scores: { avoidant: 2 } },
      { label: 'Mostly when they can’t fully have me', sub: 'Distance or obstacles can intensify attraction', scores: { fearful: 2 } },
      { label: 'Rarely — and cautiously', sub: 'I evaluate feelings carefully before trusting them', scores: { avoidant: 1, fearful: 1 } },
    ],
    motivation: 'Continue →',
  },
  {
    id: 'marriage_timeline',
    type: 'qcm',
    chapter: 'Chapter V — What you want',
    title: 'If you met a compatible partner, what marriage timeline would feel right?',
    subtitle: 'There is no correct pace. This helps compare your goals with the people you date.',
    options: [
      { label: 'Within a year', sub: 'I would prefer a relatively fast, intentional path', scores: { anxious: 1 } },
      { label: '1 – 2 years', sub: 'Enough time to build evidence without remaining indefinite', scores: { secure: 1 } },
      { label: '3+ years', sub: 'I prefer a longer period before marriage', scores: { avoidant: 1 } },
      { label: 'I want it — but the thought scares me', sub: 'The goal and the vulnerability both feel significant', scores: { fearful: 2 } },
    ],
    motivation: 'Continue →',
  },
  {
    id: 'children_dream',
    type: 'qcm',
    chapter: 'Chapter V — What you want',
    title: 'How do you currently feel about having children?',
    subtitle: 'This is included only to understand your relationship goals and timing.',
    options: [
      { label: 'I dream of it constantly', sub: 'Creating a family is a central goal', scores: { anxious: 1, secure: 1 } },
      { label: 'Yes — with the right man, at the right time', sub: 'I want children in a compatible, stable relationship', scores: { secure: 2 } },
      { label: 'I want it but I’m running out of faith', sub: 'The desire remains, but hope or timing feels difficult', scores: { fearful: 1, anxious: 1 } },
      { label: 'Unsure — I need to feel safe first', sub: 'My answer depends on the relationship and circumstances', scores: { avoidant: 1, fearful: 1 } },
    ],
    motivation: 'One final reflection →',
  },
  {
    id: 'own_words',
    type: 'textarea',
    chapter: 'Chapter V — Your own interpretation',
    title: 'In your own words, what do you think has made relationships difficult so far?',
    subtitle: 'Use plain language. This answer is reflected back as a hypothesis, never treated as a diagnosis or proven cause.',
    placeholder: 'Honestly, I think…',
    motivation: 'Show my free Pattern Snapshot →',
  },
];
